Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -20,6 +20,20 @@ jobs:
     - uses: actions/checkout@v2
       with:
         ref: ${{ github.event.inputs.sha }}
+        
+        
+    - name: ensure sha1 ok
+      run: |
+        if git show-ref --quiet ${{ github.event.inputs.sha }};
+        then
+          echo "::error ::Must be SHA1";
+          exit 1;
+        fi
+        if ! git merge-base --is-ancestor ${{ github.event.inputs.sha }} master;
+        then
+          echo "::error ::Must be on master";
+          exit 1;
+        fi
 
     # Runs a single command using the runners shell
     - name: echo
